classdef nrSchedulerValidation
    %nrSchedulerValidation Implements the validations required for scheduling output
    %
    %   Note: This is an internal undocumented class and its API and/or
    %   functionality may change in subsequent releases.

    % Copyright 2024 The MathWorks, Inc.

    methods(Static)
        function validateDLAssignments(dlAssignments, timeFrequencyResource, schedulingInfo, scheduler)
            % Validate newTx DL assignments generated by scheduler

            % Validate presence of all the required fields in the grant
            fields = ["RNTI", "FrequencyAllocation", "W", "MCSIndex"];
            coder.internal.errorIf((~isrow(dlAssignments) && ~iscolumn(dlAssignments)) || ...
                ~all(isfield(dlAssignments, fields)), 'nr5g:nrScheduler:InvalidDLAssignment');

            % For easy acccess convert timeFrequencyResource and schedulingInfo in a
            % form where at index 'i' the information is present for carrierIndex 'i'
            for i=1:numel(timeFrequencyResource)
                ttiResource(timeFrequencyResource(i).GNBCarrierIndex) = timeFrequencyResource(i);
                ttiSchedulingInfo(timeFrequencyResource(i).GNBCarrierIndex) = schedulingInfo(i);
            end
            % Validate grant fields
            numAssignments = numel(dlAssignments);
            for i=1:numAssignments
                if ~isfield(dlAssignments(i), 'GNBCarrierIndex') || isempty(dlAssignments(i).GNBCarrierIndex)
                    dlAssignments(i).GNBCarrierIndex = 1;
                end
                dlAssignment = dlAssignments(i);
                carrierIndex = dlAssignment.GNBCarrierIndex;
                frequencyResource = ttiResource(carrierIndex).FrequencyResource;
                % RNTI validation
                rnti = dlAssignment.RNTI;
                coder.internal.errorIf(isempty(rnti), 'nr5g:nrScheduler:InvalidDLAssignment');
                validateattributes(rnti, {'numeric'}, {'integer', 'scalar'}, '', 'dlAssignment.RNTI');
                eligibleUEsCarrier = schedulingInfo(carrierIndex).EligibleUEs;
                coder.internal.errorIf(~ismember(rnti, eligibleUEsCarrier), ...
                    'nr5g:nrScheduler:IneligibleDLUE', rnti, sprintf(repmat('%d ', 1, ...
                    size(eligibleUEsCarrier,2)), eligibleUEsCarrier));

                % Frequency assignment validation
                frequencyAllocation = dlAssignment.FrequencyAllocation;
                coder.internal.errorIf(isempty(frequencyAllocation), 'nr5g:nrScheduler:InvalidDLAssignment');
                validateattributes(frequencyAllocation, {'numeric'}, {'integer'}, '', 'dlAssignment.FrequencyAllocation');
                if scheduler.SchedulerConfig.ResourceAllocationType % RAT-1
                    if numel(frequencyAllocation)~=2
                        coder.internal.error('nr5g:nrScheduler:InvalidDLFreqAllocationRAT1', sprintf(repmat('%d ', 1, ...
                            numel(frequencyAllocation)), frequencyAllocation));
                    end
                    coder.internal.errorIf(frequencyAllocation(1)<0, 'nr5g:nrScheduler:InvalidDLStartRB', frequencyAllocation(1), rnti);
                    coder.internal.errorIf(frequencyAllocation(2)<=0, 'nr5g:nrScheduler:InvalidDLNumRB', frequencyAllocation(2), rnti);
                    coder.internal.errorIf(frequencyAllocation(1)+frequencyAllocation(2)>scheduler.CellConfig(carrierIndex).NumResourceBlocks, ...
                        'nr5g:nrScheduler:InvalidDLFreqAllocationRangeRAT1', frequencyAllocation(1), frequencyAllocation(2), scheduler.CellConfig(carrierIndex).NumResourceBlocks, rnti);
                else % RAT-0
                    if ~((isrow(frequencyAllocation) || iscolumn(frequencyAllocation)) && ...
                            size(frequencyAllocation,2)==size(frequencyResource,2) && ...
                            all(ismember(frequencyResource, [0 1])))
                        coder.internal.error('nr5g:nrScheduler:InvalidDLFreqAllocationRAT0', rnti, size(frequencyResource,2));
                    end
                end

                % Precoding matrix validation
                precodingMatrix = dlAssignment.W;
                coder.internal.errorIf(isempty(precodingMatrix), 'nr5g:nrScheduler:InvalidDLAssignment');
                validateattributes(precodingMatrix, {'numeric'}, "3d", '', 'dlAssignment.W');
                numLayers = size(precodingMatrix, 1);
                numGNBAntennas = scheduler.CellConfig(carrierIndex).NumTransmitAntennas;
                coder.internal.errorIf((numLayers>4) || (numLayers>numGNBAntennas), ...
                    'nr5g:nrScheduler:InvalidDLNumLayers', rnti, numLayers, numGNBAntennas);
                numPorts = size(precodingMatrix, 2);
                coder.internal.errorIf(numPorts~=numGNBAntennas, 'nr5g:nrScheduler:InvalidDLNumPorts', rnti, numPorts, numGNBAntennas);

                % MCS validation
                mcs = dlAssignment.MCSIndex;
                coder.internal.errorIf(isempty(mcs), 'nr5g:nrScheduler:InvalidDLAssignment');
                validateattributes(mcs, {'numeric'}, {'integer', 'scalar'}, 'dlAssignment.MCSIndex');
                coder.internal.errorIf(mcs<0 || mcs>27, 'nr5g:nrScheduler:InvalidDLMCS', rnti, mcs);
            end
            % Validate that same UE is not assigned multiple times on a carrier
            rntiCarrierList = [dlAssignments.RNTI; dlAssignments.GNBCarrierIndex];
            coder.internal.errorIf(~(numel(rntiCarrierList)==numel(unique(rntiCarrierList.',"rows"))), 'nr5g:nrScheduler:MultipleDLAssignmentsUE');
        end

        function validateULGrants(ulGrants, timeFrequencyResource, schedulingInfo, scheduler)
            % Validate newTx UL grants generated by scheduler

            % Validate presence of all the required fields in the grant
            fields = ["RNTI", "FrequencyAllocation", "NumLayers", "TPMI", "MCSIndex"];
            coder.internal.errorIf((~isrow(ulGrants) && ~iscolumn(ulGrants)) || ...
                ~all(isfield(ulGrants, fields)), 'nr5g:nrScheduler:InvalidULGrant');

            % For easy acccess convert timeFrequencyResource and schedulingInfo in a
            % form where at index 'i' the information is present for carrierIndex 'i'
            for i=1:numel(timeFrequencyResource)
                ttiResource(timeFrequencyResource(i).GNBCarrierIndex) = timeFrequencyResource(i);
                ttiSchedulingInfo(timeFrequencyResource(i).GNBCarrierIndex) = schedulingInfo(i);
            end

            % Validate grant fields
            numGrants = numel(ulGrants);
            for i=1:numGrants
                if ~isfield(ulGrants(i), 'GNBCarrierIndex')|| isempty(ulGrants(i).GNBCarrierIndex)
                    ulGrants(i).GNBCarrierIndex = 1;
                end
                ulGrant = ulGrants(i);
                carrierIndex = ulGrant.GNBCarrierIndex;
                frequencyResource = ttiResource(carrierIndex).FrequencyResource;
                % RNTI validation
                rnti = ulGrant.RNTI;
                eligibleUEsCarrier = schedulingInfo(carrierIndex).EligibleUEs;
                coder.internal.errorIf(isempty(rnti), 'nr5g:nrScheduler:InvalidULGrant');
                validateattributes(rnti, {'numeric'}, {'integer', 'scalar'}, '', 'ulGrant.RNTI');
                coder.internal.errorIf(~ismember(rnti, eligibleUEsCarrier), ...
                    'nr5g:nrScheduler:IneligibleULUE', rnti, sprintf(repmat('%d ', 1, ...
                    size(eligibleUEsCarrier,2)), eligibleUEsCarrier));

                % Frequency assignment validation
                frequencyAllocation = ulGrant.FrequencyAllocation;
                coder.internal.errorIf(isempty(frequencyAllocation), 'nr5g:nrScheduler:InvalidULGrant');
                validateattributes(frequencyAllocation, {'numeric'}, {'integer'}, '', 'ulGrant.FrequencyAllocation');
                if scheduler.SchedulerConfig.ResourceAllocationType % RAT-1
                    if numel(frequencyAllocation)~=2
                        coder.internal.error('nr5g:nrScheduler:InvalidULFreqAllocationRAT1', sprintf(repmat('%d ', 1, ...
                            numel(frequencyAllocation)), frequencyAllocation));
                    end
                    coder.internal.errorIf(frequencyAllocation(1)<0, 'nr5g:nrScheduler:InvalidULStartRB', frequencyAllocation(1), rnti);
                    coder.internal.errorIf(frequencyAllocation(2)<=0, 'nr5g:nrScheduler:InvalidULNumRB', frequencyAllocation(2), rnti);
                    coder.internal.errorIf(frequencyAllocation(1)+frequencyAllocation(2)>scheduler.CellConfig(carrierIndex).NumResourceBlocks, ...
                        'nr5g:nrScheduler:InvalidULFreqAllocationRangeRAT1', frequencyAllocation(1), frequencyAllocation(2), scheduler.CellConfig(carrierIndex).NumResourceBlocks, rnti);
                else % RAT-0
                    if ~((isrow(frequencyAllocation) || iscolumn(frequencyAllocation)) && ...
                            size(frequencyAllocation,2)==size(frequencyResource,2) && ...
                            all(ismember(frequencyResource, [0 1])))
                        coder.internal.error('nr5g:nrScheduler:InvalidULFreqAllocationRAT0', rnti, size(frequencyResource,2));
                    end
                end

                % Validate number of layers
                numLayers = ulGrant.NumLayers;
                coder.internal.errorIf(isempty(numLayers), 'nr5g:nrScheduler:InvalidULGrant');
                validateattributes(numLayers, {'numeric'}, {'integer', 'scalar'}, 'ulGrant.NumLayers');
                carrierContextUE = scheduler.UEContext(rnti).ComponentCarrier(carrierIndex);
                coder.internal.errorIf((numLayers<=0) || (numLayers>4) || (numLayers>carrierContextUE.NumTransmitAntennas), ...
                    'nr5g:nrScheduler:InvalidULNumLayers', rnti, numLayers, carrierContextUE.NumTransmitAntennas);

                % Validate tpmi
                tpmi = ulGrant.TPMI;
                coder.internal.errorIf(isempty(tpmi), 'nr5g:nrScheduler:InvalidULGrant');
                validateattributes(tpmi, {'numeric'}, {'integer', 'scalar'}, 'ulGrant.TPMI');
                coder.internal.errorIf(tpmi<0 || tpmi>27, 'nr5g:nrScheduler:InvalidTPMI', rnti, tpmi);

                % MCS validation
                mcs = ulGrant.MCSIndex;
                coder.internal.errorIf(isempty(mcs), 'nr5g:nrScheduler:InvalidULGrant');
                validateattributes(mcs, {'numeric'}, {'integer', 'scalar'}, 'ulGrant.MCSIndex');
                coder.internal.errorIf(mcs<0 || mcs>27, 'nr5g:nrScheduler:InvalidULMCS', rnti, mcs);
            end
            % Validate that same UE is not assigned multiple times on a carrier
            rntiCarrierList = [ulGrants.RNTI; ulGrants.GNBCarrierIndex];
            coder.internal.errorIf(~(numel(rntiCarrierList)==numel(unique(rntiCarrierList.',"rows"))), 'nr5g:nrScheduler:MultipleULGrantsUE');
       end
    end
end